<?php
$item = $attachment->item();

$media = null;

if ($item) {
    $title = $this->plugin('escapeHtml')($item->displayTitle());
    $media = $attachment->media() ?: $item->primaryMedia();
    if (preg_match('/alt=""/', $this->thumbnail($media, $this->thumbnailType)) == 1) {
        $image = $this->thumbnail($media, $this->thumbnailType, ['alt' => $title]);
        $linked_image = $item->linkRaw($image);
    }
    else {
        $image = $this->thumbnail($media, $this->thumbnailType);
        $linked_image = $item->linkRaw($image);
    }
}

$caption = $attachment->caption();
?>
<div class="representative-image <?php echo $this->thumbnailType; ?>">
    <div class="item resource">
        <?php if ($media): ?>
            <figure>
                <?php $blockPageMeta = \AgileThemeTools\Controller\SectionManager::getBlockPageMeta($this->block); ?>
                <?php if ($blockPageMeta): ?>
                  <?php printf('<a href="%s" title="Visit %s">%s</a>',$blockPageMeta['page_url'], $blockPageMeta['page_title'], $image);  ?>
                <?php else: ?>
                  <?php echo $linked_image; ?>
                <?php endif; ?>
                <?php if ($caption): ?>
                    <figcaption><?php echo $caption; ?></figcaption>
                <?php endif; ?>
            </figure>
        <?php endif; ?>
    </div>
</div>
